### ISSUE TITLE
Installing pre-built binaries fails on Windows

### ISSUE THREAD

**Issue by AlCalzone** [mapbox/node-pre-gyp#374]
Installing a module including `node-pre-gyp` fails for me on Windows with the following error message (or similar, depending on the version)
```
node-pre-gyp WARN Pre-built binaries not installable for node-aead-crypto@1.1.3 and node@8.10.0 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error ENOTDIR: Cannot cd into 'C:\Users\domin\Documents\Visual Studio 2017\Repositories\node-dtls-client\node_modules\node-aead-crypto\build\Release\node-v57-win32-x64'
```

I've tried versions `0.9.1`, `0.7.0` and https://github.com/mapbox/node-pre-gyp/pull/371
Before that I had `0.6.38` which fails with "error downloading", although the package it tries to download is actually downloadable.

**Comment by springmeyer** [comment]
> I've tried versions 0.9.1

Can you double check and test 0.9.1 again. The `ENOTDIR: Cannot cd into` error should have been fixed by @allenluce in https://github.com/mapbox/node-pre-gyp/pull/371.

**Comment by mapsam** [comment]
@springmeyer #371 hasn't been released yet, as we're still tweaking #372 - this fix should go out in 0.9.2

**Comment by AlCalzone** [comment]
Yes @mapsam is correct, version 1.1.3 of my lib is bundling the git version of `node-pre-gyp` @ 90c5463 as you can verify with `npm pack node-aead-crypto@1.1.3`. 
This didn't fix the issue however. I can reproduce it by running
```
npm i node-aead-crypto@1.1.3
```

**Comment by allenluce** [comment]
@AlCalzone did you also package 1.1.3 with `node-pre-gyp@90c5463`? Your 1.1.3 package looks very much like your 1.1.1 package which I assume was packaged with post-7.0.0 `node-pre-gyp`

**Comment by AlCalzone** [comment]
Sorry for the late response. I'm pretty sure about that, yes. The release is done through an automated build script, so whatever is on github under a tag should also be released under that version:
v1.1.3:
https://github.com/AlCalzone/node-aead-crypto/blob/d7f0e56c725665460e623f1ce598ec8995fd1424/package.json#L38

v1.1.2:
https://github.com/AlCalzone/node-aead-crypto/blob/98645bd5d477b861f9e4c2b1d429b73a7720ba44/package.json#L38

v1.1.1:
https://github.com/AlCalzone/node-aead-crypto/blob/2027cb3810064ac95c78726df8cc260295bab68a/package.json#L38
